version: '3'
services:
  # nextjsの環境
  nuxt-app:
    build:
      context: ./Docker/nextjs/
    tty: true
    volumes:
      - ./nextjs:/app/src/nextjs
    working_dir: /app/src/nextjs
    environment:
     - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"
  
  # reactの環境
  react-app:
    build:
      context: ./Docker/react/
    volumes:
      - ./reactApp:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "3001:3001"
    stdin_open: true 
    environment:
      - CHOKIDAR_USEPOLLING=true
